language: python
sudo: false
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
install:
    - pip install -U pip wheel coverage codecov
    - pip install -r requirements.txt pytest pytest-mock
    - python setup.py develop
script:
    - coverage run -m py.test -v tests/ && codecov
cache:
    directories:
        - $HOME/.cache/pip
